title: Streamdata Gallery Google Apps Admin SDK
url: google-apps-admin-sdk.streamdata.gallery
tag: Google Apps Admin SDK
markdown: kramdown
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", ".DS_Store"]
github_user: streamdata-gallery
github_repo: google-apps-admin-sdk
github_branch: master
collections:
  listings:
    output: true
    permalink: /listings/:path/
defaults:
  - scope:
      type: listings
    values:
      layout: listings
